# Generated by Django 5.2.4 on 2025-08-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_product_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='unit',
        ),
    ]
