# Generated by Django 5.2.4 on 2025-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit',
            field=models.CharField(choices=[('Brass', 'Brass'), ('Ton', 'Ton'), ('Cubic Meter', 'Cubic Meter')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
